feat: add user data class, view model and repository; tests in progress
The repository test fails to build due to a 'java.lang.NoClassDefFoundError', this will need fixing.
The classes are not yet documented and tests are not yet complete.